name: 02 - Workflow Event
on:
  push:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "I was triggered by ${{github.event_name}}"