name: 13 - caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        default: true
        description: Enable/disable cache
        type: boolean
      node-version:
        required: true
        description: Node version to use
        type: choice
        options:
          - '21.x'
          - '20.x'
          - '18.x'
          - '16.x'
        default: '21.x'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        if: ${{ inputs.use-cache == true }}
        id: cache
        uses: actions/cache@v4
        with:
          path: 13-caching/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Testing
        run: |
          npm run test
      - name: Building
        run: |
          npm run build
      - name: Deploying to none prod
        run: |
          echo "Deploying...."